export const categoryCode = [
  {code: "MT1", name:["대형마트", "마트", "가게"]},
  {code: "CS2", name: ["편의점"]},
  {code: "PS3", name: ["어린이집", "유치원"]},
  {code: "SC4", name: ["학교", "중학교", "고등학교", "대학교"]},
  {code: "AC5", name: ["학원"]},
  {code: "PK6", name: ["주차장"]},
  {code: "OL7", name: ["주유소", "충전소"]},
  {code: "SW8", name: ["지하철역", "역"]},
  {code: "BK9", name: ["은행"]},
  {code: "CT1", name: ["문화시설"]},
  {code: "AG2", name: ["중개업소"]},
  {code: "PO3", name: ["공공기관"]},
  {code: "AT4", name: ["관광명소"]},
  {code: "AD5", name: ["숙박"]},
  {code: "FD6", name: ["음식점"]},
  {code: "CE7", name: ["카페"]},
  {code: "HP8", name: ["병원"]},
  {code: "PM9", name: ["약국"]},
];
