name : front-test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug step
        run: echo "Debug information here"
      - name: front Build and deploy
        run: |
          cd trizzle-front
          echo "VITE_KAKAO_API_KEY=${{ secrets.VITE_KAKAO_API_KEY }}" >> .env
          rm -rf .yarnrc.yml
          yarn set version 3.6.1
          npm install
          yarn add
          yarn build
        env:
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}