version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my-network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    environment:
      - SPRING_DATA_ELASTICSEARCH_HOST=elasticsearch
      - SPRING_DATA_ELASTICSEARCH_PORT=9200
    networks:
      - my-network

networks:
  my-network:
    driver: bridge