name : front-test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4.0.0
      - name: Debug step
        run: echo "Debug information here"
      - name : yarn berry set and build
        run: |
          cd trizzle-front
          echo "VITE_KAKAO_API_KEY=${{ secrets.VITE_KAKAO_API_KEY }}" >> .env
          rm -rf .yarnrc.yml
          corepack enable
          corepack prepare yarn@3.6.1 --activate
          yarn set version 3.6.1
          yarn
          yarn install
          npm install
          yarn build
        env:
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
