name : front-test

on:
  push:
    branches:
      - develop
    paths:
      - trizzle-front/**

  pull_request:
    branches:
      - develop
    paths:
      - trizzle-front/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 18.16.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.x'
          # cache: 'yarn'
      - name: Debug step
        run: echo "Debug information here"
        
      - name : yarn berry set
        run: |
          cd trizzle-front
          echo "VITE_KAKAO_API_KEY=${{ secrets.VITE_KAKAO_API_KEY }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          # rm -rf .yarnrc.yml
          # corepack enable
          # corepack prepare yarn@3.6.1 --activate
          # yarn set version 3.6.1
        env:
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name : front file dir
        run: |
          cd trizzle-front
          ls -al
          
      # - name: Get cache dir path
      #   id: yarn-cache-dir-path
      #   run: echo "CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV
      
      # - name: Yarn cache
      #   uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: |
      #       ${{ steps.yarn-cache-dir-path.outputs.CACHE_DIR }}
      #       trizzle-front/.yarn/cache
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('trizzle-front/yarn.lock') }}-${{ steps.set-version.outputs.YARN_VERSION }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-${{ hashFiles('trizzle-front/yarn.lock') }}-
      
      - name: Install dependencies
        run: |
          cd trizzle-front
          yarn install
            
      - name : yarn build
        run: |
          cd trizzle-front
          yarn build

      - name: Package Application
        if: github.event_name == 'push'
        run: cd trizzle-front && tar -czvf dist.tar.gz dist

      - name: copy file to ssh
        if: github.event_name == 'push'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  
          username: ${{ secrets.SERVER_NAME }} 
          key: ${{ secrets.SSH_PEM_KEY }}
          source: "trizzle-front/dist.tar.gz"
          target: ${{ secrets.SERVER_PATH }}

      - name: execute shell script
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          script: "cd ../BuildFiles; ./front-build-script.sh"