name : front-test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Setup Node 18.16.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '18.19.x'
      #     cache: 'yarn'
      - name: Debug step
        run: echo "Debug information here"
        
      - name : yarn berry set
        run: |
          cd trizzle-front
          echo "VITE_KAKAO_API_KEY=${{ secrets.VITE_KAKAO_API_KEY }}" >> .env
          run: echo 'nodeLinker: node-modules' >> .yarnrc.yml
          # rm -rf .yarnrc.yml
          # corepack enable
          # corepack prepare yarn@3.6.1 --activate
          # yarn set version 3.6.1
        env:
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name : front file dir
        run: |
          cd trizzle-front
          ls -al
          yarn -v
          node -v
          
      # - name: Get cache dir path
      #   id: yarn-cache-dir-path
      #   run: echo "CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV
      
      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: trizzle-front/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('trizzle-front/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install dependencies
        run: |
          cd trizzle-front
          yarn install
            
      - name : yarn build
        run: |
          cd trizzle-front
          yarn build
